context:
  version: 1.0.12

package:
  name: libmpack-lua
  version: ${{ version }}

source:
  url: https://github.com/libmpack/libmpack-lua/releases/download/${{ version }}/libmpack-lua-${{ version }}.tar.gz
  sha256: 06b662b1f14cfaf592ecb3fab425bef20e51439509b7a1736a790ecc929ef8bf

build:
  number: 0
  skip: win
  dynamic_linking:
    rpaths:
      - lib/lua/5.1/
      - lib/

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - luarocks
    - luajit-openresty
  run:
    - luajit-openresty

tests:
  - script:
      - "luajit -e \"require 'mpack'\""

about:
  license: MIT
  license_file: LICENSE-MIT
  summary: libmpack lua binding
  homepage: https://github.com/libmpack/libmpack-lua

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
